en:
  welcome: "Welcome to Calculator! Enter your name:"
  valid_name: "Make sure to enter a valid name"
es:
  welcome: "Bienvenido a la calculadora! Favor de ingresar su nombre:"
  valid_name: "Asegúrese de ingresar un nombre válido:"